[build-system]
requires = ["setuptools>=45.0.0", "wheel", "setuptools_scm[toml]>=6.0"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 79
preview = true
unstable = true
exclude = "src/zorg/grammar/"

[tool.pydocstyle]
match = '.*\.py'
match-dir = '(?!src/zorg/grammar)'
select = [
    "D100",
    "D101",
    "D102",
    "D103",
    "D104",
    "D105",
    "D106",
    "D412",
    "D414",
    "D416",
    "D417",
]
