"""This package's contents are auto-generated by ANTLR.

We expect this package to contain a lexer, parser, and listener that we can use
to interpret Zorg queries. For example, to show all A-priority open todos:

Examples
--------
// Show all open 'P0', 'P1', or 'P2' priority todos, grouped by file.
W P0-2 G file

// Show all people involved with the +foobar project.
S % W +foobar
"""
