"""This package's contents are auto-generated by ANTLR.

We expect this package to contain a lexer, parser, and listener that we can use
to interpret Zorg queries. For example, to show all A-priority open todos:

Examples
--------
// Show all open 'A' and 'B' priority todos, grouped by file.
W [#A-B] G file

// Show all people involved with the +foobar project.
S people W +foobar
"""
